/* Pay for Layers — gallery.
   Driven entirely by manifest.json (generated by tools/build-library.mjs), so
   adding artwork never means editing this file.

   Free tier  = the PNG, downloaded straight from this repo.
   Paid tier  = the SVG, which lives behind Stripe and never ships here. */

(() => {
  "use strict";

  const MANIFEST = "manifest.json";

  const els = {
    grid: document.getElementById("gallery-grid"),
    search: document.getElementById("gallery-search"),
    filters: document.getElementById("gallery-filters"),
    count: document.getElementById("gallery-count"),
    toast: document.getElementById("toast"),
  };
  if (!els.grid) return;

  let items = [];
  let pro = {};
  let category = "all";
  let query = "";

  /* --- helpers ----------------------------------------------------------- */

  const esc = (s) =>
    String(s).replace(/[&<>"']/g, (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c])
    );

  const kb = (bytes) =>
    bytes >= 1024 * 1024
      ? (bytes / 1024 / 1024).toFixed(1) + " MB"
      : Math.max(1, Math.round(bytes / 1024)) + " KB";

  let toastTimer;
  function toast(message) {
    if (!els.toast) return;
    els.toast.textContent = message;
    els.toast.dataset.show = "true";
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => (els.toast.dataset.show = "false"), 2600);
  }

  async function copy(text) {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      const ta = document.createElement("textarea");
      ta.value = text;
      ta.setAttribute("readonly", "");
      ta.style.cssText = "position:fixed;top:-1000px;opacity:0";
      document.body.appendChild(ta);
      ta.select();
      let ok = false;
      try { ok = document.execCommand("copy"); } catch { ok = false; }
      ta.remove();
      return ok;
    }
  }

  /** Every route to checkout goes through here, so an unset link fails safely. */
  function checkout(source) {
    if (!pro.checkout_url) {
      toast("Checkout isn’t live yet — email " + (pro.email || "carlos@carlospx.com"));
      return;
    }
    const url = new URL(pro.checkout_url);
    url.searchParams.set("ref", source);
    window.open(url.toString(), "_blank", "noopener");
  }

  /* --- icons ------------------------------------------------------------- */

  const ICONS = {
    download: '<path d="M10 3v9"/><path d="m6.5 9 3.5 3.5L13.5 9"/><path d="M4 15.5h12"/>',
    lock: '<rect x="4.5" y="8.5" width="11" height="8" rx="1.5"/><path d="M7 8.5V6a3 3 0 0 1 6 0v2.5"/>',
    link: '<path d="M8.5 11.5a3 3 0 0 0 4.24 0l2.76-2.76a3 3 0 0 0-4.24-4.24l-1 1"/><path d="M11.5 8.5a3 3 0 0 0-4.24 0L4.5 11.26a3 3 0 0 0 4.24 4.24l1-1"/>',
  };
  const icon = (n) =>
    `<svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.6" ` +
    `stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICONS[n]}</svg>`;

  /* --- rendering --------------------------------------------------------- */

  function cardHTML(item) {
    return `
      <figure class="card" data-id="${esc(item.id)}">
        <div class="card__art">
          <img src="${esc(item.png)}" alt="${esc(item.title)} — hand-drawn illustration"
               loading="lazy" decoding="async" width="240" height="240">
          <button class="card__copy" data-act="url" title="Copy the direct link"
                  aria-label="Copy the direct link to ${esc(item.title)}">${icon("link")}</button>
        </div>
        <figcaption class="card__body">
          <div class="card__id">
            <span class="card__title" title="${esc(item.title)}">${esc(item.title)}</span>
            <span class="card__meta">${item.width}&thinsp;&times;&thinsp;${item.height} · ${kb(item.bytes)}</span>
          </div>
          <div class="card__actions">
            <a class="pill pill--free" href="${esc(item.png)}" download="${esc(item.id)}.png"
               data-act="png" aria-label="Download ${esc(item.title)} as a free PNG">
              ${icon("download")}<span>PNG</span><span class="pill__tag">free</span>
            </a>
            <button class="pill pill--pro" data-act="pro"
                    aria-label="Get the editable SVG of ${esc(item.title)}">
              ${icon("lock")}<span>SVG</span>
            </button>
          </div>
        </figcaption>
      </figure>`;
  }

  function render() {
    const q = query.trim().toLowerCase();
    const visible = items.filter(
      (i) =>
        (category === "all" || i.category === category) &&
        (!q || i._search.includes(q))
    );

    els.grid.innerHTML = visible.length
      ? visible.map(cardHTML).join("")
      : `<div class="gallery-empty" style="grid-column:1/-1">
           <p><strong>Nothing matches “${esc(query)}”.</strong></p>
           <p style="margin-top:8px">Try a broader word, or clear the filters.</p>
         </div>`;

    if (els.count) {
      els.count.textContent =
        visible.length === items.length
          ? `${items.length} illustrations`
          : `${visible.length} of ${items.length}`;
    }
  }

  function buildFilters(categories) {
    if (!els.filters) return;
    els.filters.innerHTML = ["all", ...categories]
      .map(
        (c) =>
          `<button class="chip" data-cat="${esc(c)}" aria-pressed="${c === "all"}">` +
          `${esc(c === "all" ? "All" : c[0].toUpperCase() + c.slice(1))}</button>`
      )
      .join("");
  }

  /* --- events ------------------------------------------------------------ */

  els.grid.addEventListener("click", async (e) => {
    const btn = e.target.closest("[data-act]");
    if (!btn) return;
    const card = btn.closest(".card");
    const item = items.find((i) => i.id === card.dataset.id);
    if (!item) return;

    if (btn.dataset.act === "png") {
      toast(`Downloading ${item.title}.png — credit goes in the file’s metadata`);
      return; // the anchor's download attribute does the rest
    }

    e.preventDefault();

    if (btn.dataset.act === "pro") {
      checkout("card-" + item.id);
      return;
    }

    if (btn.dataset.act === "url") {
      const ok = await copy(item.url);
      toast(ok ? "Direct link copied" : "Could not reach the clipboard");
    }
  });

  els.search?.addEventListener("input", (e) => {
    query = e.target.value;
    render();
  });

  els.filters?.addEventListener("click", (e) => {
    const chip = e.target.closest(".chip");
    if (!chip) return;
    category = chip.dataset.cat;
    els.filters.querySelectorAll(".chip").forEach((c) =>
      c.setAttribute("aria-pressed", String(c === chip))
    );
    render();
  });

  /* Every buy button on the page, wherever it lives. */
  document.addEventListener("click", (e) => {
    const buy = e.target.closest("[data-checkout]");
    if (!buy) return;
    e.preventDefault();
    checkout(buy.dataset.checkout || "page");
  });

  /* Copy buttons for the code snippets. */
  document.addEventListener("click", async (e) => {
    const btn = e.target.closest("[data-copy]");
    if (!btn) return;
    const src = document.getElementById(btn.dataset.copy);
    if (!src) return;
    const ok = await copy(src.textContent.trim());
    const original = btn.textContent;
    btn.textContent = ok ? "Copied" : "Copy failed";
    setTimeout(() => (btn.textContent = original), 1600);
  });

  /* --- boot -------------------------------------------------------------- */

  fetch(MANIFEST)
    .then((r) => {
      if (!r.ok) throw new Error(r.status);
      return r.json();
    })
    .then((data) => {
      pro = { ...data.pro, email: data.author?.email };
      items = (data.illustrations || []).map((i) => ({
        ...i,
        _search: [i.title, i.id, i.category, ...(i.tags || [])].join(" ").toLowerCase(),
      }));
      buildFilters(data.categories || []);
      render();

      document.querySelectorAll("[data-total]").forEach((el) => (el.textContent = items.length));
      document.querySelectorAll("[data-price]").forEach((el) => (el.textContent = pro.price || ""));
      if (!pro.checkout_url) {
        document.querySelectorAll("[data-checkout]").forEach((el) => (el.dataset.pending = "true"));
      }
    })
    .catch(() => {
      els.grid.innerHTML = `<div class="gallery-empty" style="grid-column:1/-1">
        <p><strong>The library index could not be loaded.</strong></p>
        <p style="margin-top:8px">Every PNG is still there at
        <a href="png/" style="text-decoration:underline">/png/</a>.</p>
      </div>`;
    });
})();
